version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: productsdb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
